export enum Prec {
  SubtractionType = -1,
  UnionType = 0,
  Assignment = 1,
  TypeHint = 1,
  CurriedType = 1,
  NamedInfixApplication = 1,
  SectionIdentifier = 1,
  Literal = 1,
  IntersectionType = 1,
  LabeledType = 2,
  OperatorInfixApplication = 2,
  OptionalType = 3,
  Biconditional = 3,
  TaggedType = 4,
  Implication = 4,
  Or = 5,
  And = 6,
  Equality = 7,
  Order = 8,
  Mod = 9,
  Sum = 10,
  Product = 11,
  Exponentiation = 12,
  Not = 13,
  InfixApplication = 14,
  PrefixApplication = 15,
  Application = 16,
  Term = 17,
  Pattern = 17,
  Access = 18,
  Pipeline = 19,
  ParametricTypeInstance = 20,
}

export enum Dialect {
  DTN,
  Tony,
}
