export enum Prec {
  Group = -1,
  SubtractionType = -1,
  UnionType = 0,
  Assignment = 1,
  TypeHint = 1,
  CurriedType = 1,
  NamedInfixApplication = 1,
  SectionIdentifier = 1,
  Literal = 1,
  IntersectionType = 1,
  LabeledType = 2,
  OperatorInfixApplication = 2,
  OptionalType = 3,
  Biconditional = 3,
  TaggedType = 4,
  Implication = 4,
  Difference = 5,
  Or = 6,
  And = 7,
  Equality = 8,
  Order = 9,
  Mod = 10,
  Sum = 11,
  Product = 12,
  Exponentiation = 13,
  Not = 14,
  InfixApplication = 15,
  Application = 16,
  Term = 17,
  Pattern = 17,
  Access = 18,
  Pipeline = 19,
  ParametricTypeInstance = 20,
  Argument = 21,
  Hole = 22,
}

export enum Dialect {
  DTN,
  Tony,
}
