export enum Prec {
  Group = -1,
  SubtractionType = -1,
  UnionType = 0,
  Assignment = 1,
  TypeHint = 0,
  CurriedType = 1,
  NamedInfixApplication = 1,
  SectionIdentifier = 1,
  Literal = 1,
  IntersectionType = 1,
  LabeledType = 2,
  OperatorInfixApplication = 2,
  OptionalType = 3,
  Biconditional = 3,
  TaggedType = 4,
  Implication = 4,
  Or = 5,
  And = 6,
  Equality = 7,
  Order = 8,
  Mod = 9,
  Sum = 10,
  Product = 11,
  Exponentiation = 12,
  Not = 13,
  InfixApplication = 14,
  Application = 15,
  Term = 16,
  Pattern = 16,
  Access = 17,
  Pipeline = 18,
  ParametricTypeInstance = 19,
  Argument = 20,
  Hole = 21,
}

export enum Dialect {
  DTN,
  Tony,
}
