name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - '10.x'
          - '11.x'
          - '12.x'
          - '13.x'

    name: Node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install Tree-sitter
      run: yarn global add tree-sitter-cli
    - name: Generate parser
      run: yarn generate
    - name: Test rebuild
      run: yarn install
    - name: Prettier
      run: yarn lint
    - name: TypeScript
      run: yarn tsc
    - name: Test parser
      run: yarn test
