name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - '12.x'
          - '13.x'
          - '14.x'
          - '15.x'

    name: Node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2.1.4
      with:
        node-version: ${{ matrix.node }}
    - name: Setup
      run: yarn setup
    - name: Generate type declarations
      run: yarn types
    - name: Type declaration are up-to-date
      run: |
        files=$(git update-index --refresh)
        echo "Files: "
        echo $files
        if [[ -n $files ]]; then
          exit 1
        fi
    - name: Prettier
      run: yarn prettierlint
    - name: ESLint
      run: yarn eslint
    - name: Test parser
      run: yarn test
