name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - '12.x'
          - '13.x'
          - '14.x'
          - '15.x'

    name: Node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node }}
    - name: Setup
      run: yarn setup
      allow_failure: true
    - name: Generate type declarations
      run: yarn types
    - name: Type declarations are up-to-date
      run: |
        changes=$(git diff -- **/*.d.ts)
        if [[ -n $changes ]]; then
          echo "$changes"
          exit 1
        fi
    - name: Prettier
      run: yarn prettierlint
    - name: ESLint
      run: yarn eslint
    - name: Test parser
      run: yarn test
