name: Prebuild

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          # - macOS-latest
        node_version:
          - 12
          - 13
          - 14
          - 15

    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2.1.4
      with:
        node-version: ${{ matrix.node_version }}
    - name: Setup
      run: yarn setup

    - name: Build binaries and upload to GitHub (Linux/macOS)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: yarn prebuild --all -u $PREBUILD_TOKEN
      env:
        PREBUILD_TOKEN: ${{ secrets.PREBUILD_TOKEN }}
    - name: Build binaries and upload to GitHub (Windows)
      if: runner.os == 'Windows'
      run: yarn prebuild --all -u ${env:PREBUILD_TOKEN}
      env:
        PREBUILD_TOKEN: ${{ secrets.PREBUILD_TOKEN }}
