name: Prebuild

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          # - macOS-latest

    name: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v3.1.0
      with:
        node-version: 15
    - name: Setup
      run: yarn setup
      shell: bash {0}

    - name: Build binaries and upload to GitHub (Linux/macOS)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: yarn prebuild --all -u $PREBUILD_TOKEN
      env:
        PREBUILD_TOKEN: ${{ secrets.PREBUILD_TOKEN }}
    - name: Build binaries and upload to GitHub (Windows)
      if: runner.os == 'Windows'
      run: yarn prebuild --all -u ${env:PREBUILD_TOKEN}
      env:
        PREBUILD_TOKEN: ${{ secrets.PREBUILD_TOKEN }}
