name: Release

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    name: NPM
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2.4.1
      with:
        node-version: 15
        registry-url: https://registry.npmjs.org/
    - name: Setup
      run: yarn setup
      shell: bash {0}
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
