name: Release

on:
  release:
    types: [published]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    name: GPR
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2.1.2
      with:
        node-version: 14
        registry-url: https://npm.pkg.github.com/
        scope: '@jonhue'
    - name: Setup
      run: yarn setup
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GPR_AUTH_TOKEN }}

  publish-npm:
    runs-on: ubuntu-latest
    name: NPM
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2.1.2
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org/
    - name: Setup
      run: yarn setup
    - name: Generate type declarations
      run: yarn types
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
