name: Release

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    name: NPM
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2.1.3
      with:
        node-version: 15
        registry-url: https://registry.npmjs.org/
    - name: Setup
      run: yarn setup
    - name: Generate type declarations
      run: yarn types
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
